Repository bringyourownideas/silverstripe-composer-security-checker, pull requests merged in 2018-06, with the labels that each got.

#38 Update readme to reflect v1.0 milestone changes
  README.md
Labels: affects/v3, type/docs

#40 DOCS Link to user guide of maintenance module
  README.md
Labels: affects/v3, type/docs

#39 API Remove updateSummary, move alerts into a data schema extension
  _config/extensions.yml
  src/Extensions/PackageSecurityExtension.php
  templates/PackageSecurityAlerts.ss
  templates/SecurityAlertSummary.ss
  tests/Extensions/PackageSecurityExtensionTest.php
  tests/Extensions/PackageSecurityExtensionTest.yml
Labels: affects/v4, change/major

#41 Add integration tests for DataExtensions applied
  .travis.yml
  src/Extensions/PackageSecurityExtension.php
  templates/SecurityAlertSummary.ss
  tests/PackageSecurityExtensionTest.php
  tests/PackagesWithAlerts.yml
  tests/SecurityAlertExtensionTest.php
  tests/SiteSummaryExtensionTest.php
  tests/Stubs/SiteSummaryAlertStub.php
Labels: affects/v3, change/minor

#43 FIX Use FQCN in dependency string
  src/Tasks/SecurityAlertCheckTask.php
Labels: affects/v3, change/patch
